package ui

import "github.com/charmbracelet/lipgloss"

const (
	colorPanelBorder     = lipgloss.Color("63")
	colorTitleText       = lipgloss.Color("86")
	colorMutedText       = lipgloss.Color("82")
	colorSuccessText     = lipgloss.Color("42")
	colorWarningText     = lipgloss.Color("214")
	colorErrorText       = lipgloss.Color("196")
	colorInfoText        = lipgloss.Color("81")
	colorHighlightText   = lipgloss.Color("75")
	colorRunStateDone    = lipgloss.Color("24")
	colorRunStateRunning = lipgloss.Color("42")
	colorRunStateStop    = lipgloss.Color("214")
	colorSelectedText    = lipgloss.Color("229")
	colorSelectedBg      = lipgloss.Color("63")
	colorStatusBarBg     = lipgloss.Color("17")
	colorStatusBarGreen  = lipgloss.Color("46")
	colorStatusBarRed    = lipgloss.Color("196")
	colorStatusBarYellow = lipgloss.Color("226")
	colorStatusBarText   = lipgloss.Color("255")
)

var (
	panelStyle        = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(colorPanelBorder).Padding(0, 1)
	titleStyle        = lipgloss.NewStyle().Foreground(colorTitleText).Bold(true)
	dimStyle          = lipgloss.NewStyle().Foreground(colorMutedText)
	okStyle           = lipgloss.NewStyle().Foreground(colorSuccessText)
	warnStyle         = lipgloss.NewStyle().Foreground(colorWarningText)
	errStyle          = lipgloss.NewStyle().Foreground(colorErrorText)
	infoStyle         = lipgloss.NewStyle().Foreground(colorInfoText)
	blueStyle         = lipgloss.NewStyle().Foreground(colorHighlightText)
	runStateDoneStyle = lipgloss.NewStyle().Foreground(colorRunStateDone)
	runStateRunStyle  = lipgloss.NewStyle().Foreground(colorRunStateRunning)
	runStateStopStyle = lipgloss.NewStyle().Foreground(colorRunStateStop)
	selectedStyle     = lipgloss.NewStyle().Foreground(colorSelectedText).Background(colorSelectedBg).Bold(true)
	statusBarStyle    = lipgloss.NewStyle().Background(colorStatusBarBg).Foreground(colorStatusBarText).Bold(true).Padding(0, 1)
	runningStyle      = lipgloss.NewStyle().Background(colorStatusBarGreen).Foreground(colorStatusBarBg).Bold(true)
	idleStyle         = lipgloss.NewStyle().Background(colorStatusBarRed).Foreground(colorStatusBarText).Bold(true)
	externalStyle     = lipgloss.NewStyle().Background(colorStatusBarYellow).Foreground(colorStatusBarBg).Bold(true)
)
